version: '3'

volumes:
  go-post-volume:
    external: true

services:
  app:
    build: .
    working_dir: /go/src/app/main
    command: bash --login
    # command: dev_appserver.py app.yaml --host 0.0.0.0
    # command: go build && ./main
    # command: dlv debug --headless --listen=:2345 --api-version=2
    volumes:
      - go-post-volume:/go/src/app
      - ./gcloud/service-account-key.json:/tmp/service-account-key.json
    environment:
      TZ: Asia/Tokyo
    ports:
      - 8080:8080 # AppEngine default
      - 2345:2345 # Debug
    tty: true
    privileged: true
