version: 2.1

orbs:
  gcp-cli: circleci/gcp-cli@1.0.3

executors:
  golang:
    working_directory: /go
    docker:
      - image: circleci/golang:1.11
  gcloud:
    working_directory: /go
    docker:
      - image: google/cloud-sdk:latest

commands:
  give_execute_permission_to_appcfg:
    steps:
      - run:
          name: appcfg.pyに実行権限を付与
          command: chmod +x /usr/lib/google-cloud-sdk/platform/google_appengine/appcfg.py

jobs:
  deploy:
    executor: gcloud
    working_directory: ~
    environment:
      FOO: bar
    steps:
      - checkout
      - gcp-cli/initialize
      - give_execute_permission_to_appcfg
      - run:
          name: デプロイの実施
          working_directory: ~/project/src/app
          command: |
            echo $PWD
            make update version=$CIRCLE_SHA1
            make migrate version=$CIRCLE_SHA1

workflows:
  deploy_to_production:
    jobs:
      - deploy:
          filters:
            branches:
              only: '#38'
